### ISSUE TITLE
pretrain

### ISSUE THREAD

**Issue by nvlong21** [Ontheway361/antispoof-single-image#4]
Thank for repo
Can you share pretrain model?

**Comment by Ontheway361** [comment]
@nvlong21 there is a pretrained model that was trained on SiW, you can download with following link and pwd:
link:https://pan.baidu.com/s/16uSe110mxILtk9PO4wlLjg  pwd:s457

**Comment by nvlong21** [comment]
thanks you!

**Comment by luan1412167** [comment]
Hi @Ontheway361, @nvlong21 ,
I can't download model on baidu. Do you share a drive link for downloading? Many thanks.

**Comment by Ontheway361** [comment]
@luan1412167 ，Hi，Old Fe, this is the google dirve link[[passdoor](https://drive.google.com/file/d/1OY4ySLWIoEzWcqit9mruMRyfLQguDCV5/view?usp=sharing)]. just enjoy.

**Comment by luan1412167** [comment]
@Ontheway361 thanks for your quick reply. I'm highly appreciated your repo.

**Comment by mahq195** [comment]
@Ontheway361 @luan1412167 can i ask you a question: is that the file dir _'/home/jovyan/jupyter/checkpoints_zoo/face-antisp/single-1.0/siw_baseline/sota.pth'_ ?
