### ISSUE TITLE
Request pretrained model on SiW

### ISSUE THREAD

**Issue by WindQingYang** [Ontheway361/antispoof-single-image#7]
I am very interested in your work, will you share the pretrained model on SiW since I got below issue?

FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/jupyter/checkpoints_zoo/face-antisp/single-1.0/siw_baseline/sota.pth'

**Comment by WindQingYang** [comment]
Got, thanks

**Comment by Doanhdz** [comment]
@WindQingYang  Can you share me the sota.pth ?

**Comment by ivanfadillahgdp** [comment]
How do you solve that?
